# Generated by Django 5.2.6 on 2025-09-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorprofile',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructor'},
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
